Changed order of Allstar-node database fields in 'getdb'. Displayed data from Allstar-node db (if available) in 'astar' output.

diff --git a/astar b/astar
--- a/astar
+++ b/astar
@@ -13,7 +13,14 @@
 #                     to this code to switch). Added ability to show connectedness (as a
 #                     prelude to using graphviz to draw a bubble graph!) by specifying
 #                     a "-b" command-line argument.
+# 2018-12-13  msipin  Added per-node detail (taken from "Allstar db" generated by "getdb"
+#                     tool in this same repository).
 ##############################
+
+# Local copy of Allstar node database (CAUTION: might not exist! Don't assume it does!)
+# NOTE: THIS MUST MATCH WHAT IS SPECIFIED IN "getdb"!!
+ALLSTAR_NODE_DB=/var/tmp/nodes.db
+
 
 SEED_NODE_NUMBER=""
 
@@ -25,7 +32,18 @@ BUBBLES_ARG="-b"
 WGET_TIMEOUT=20			# Looking up one node
 WGET_FULL_LIST_TIMEOUT=60	# Grabbing entire "node list"
 
-# Check for "draw bubbles" first!
+
+
+tmp_file1=/dev/shm/astar.$$.1
+tmp_file2=/dev/shm/astar.$$.2
+
+#trap "rm -f $tmp_file1 $tmp_file2; exit 0" 0 1 2 3 6 12 15
+
+
+rm -f $tmp_file1 $tmp_file2
+
+
+# NOTE: *MUST* check for "draw bubbles" before doing any more command-line-argument processing!
 if [ $# -ge 1 -a ""$1"" = ""$BUBBLES_ARG"" ]
 then
 	# User wants bubbles!
@@ -127,6 +145,9 @@ done
 
 if [ ""$DRAW_CONNECTIVITY"" -eq 0 ]
 then
+
+  rm -f $tmp_file1
+
   # Set to "1" to use DNS/dig technique
   # Set to "0" to use HTTP GET technique
   if [ 1 ]
@@ -136,7 +157,7 @@ then
 	for NODE in ${master_list}
 	do
 		dig ${NODE}.nodes.hamvoip.org txt | egrep -v "^;|^\." |grep TXT | awk -F"@" '{ print $2 }' | sed "s/\// /g" | sed "s/,/ /g" | awk '{ print $2,$1 }'
-	done | sort -n
+	done | sort -n >> $tmp_file1
   else
 	# Display total list of interconnected nodes using wget from nodes.pl URL -
 	# NOTE: You can also get this info from http://nodes(x).allstarlink.org/cgi-bin/nodes.pl
@@ -156,8 +177,36 @@ then
 	##echo "DEBUG: egrep_str - $egrep_str"
 
 	# Use egrep pattern against wget results from nodes(x).....nodes.pl -
-	wget --timeout=${WGET_FULL_LIST_TIMEOUT} -q -O- http://nodes1.allstarlink.org/cgi-bin/nodes.pl | egrep "${egrep_str}" | sed "s/=radio@/ /g" | awk -F"/" '{ print $1 }' | sort -n
+	wget --timeout=${WGET_FULL_LIST_TIMEOUT} -q -O- http://nodes1.allstarlink.org/cgi-bin/nodes.pl | egrep "${egrep_str}" | sed "s/=radio@/ /g" | awk -F"/" '{ print $1 }' | sort -n >> $tmp_file1
   fi
+
+
+rm -f $tmp_file2
+touch $tmp_file2
+
+# If Allstar node database exists, and non-zero-length...
+if [ -s ""$ALLSTAR_NODE_DB"" ]
+then
+
+  # Generate per-node data
+  for NODE in ${master_list}
+  do
+	# Only get rid of the first two field-separator characters. This will allow merge on the "node" field
+	grep "^|${NODE}|" $ALLSTAR_NODE_DB | sed "s/|//" | sed "s/|/ |/"
+  done | sort -n >> $tmp_file2
+fi
+
+# Merget the two sources of data
+  join -a1 $tmp_file1 $tmp_file2 | awk '{
+
+for (i=1;i<=NF;i++) {
+  if (i==1) printf "%-7s", $i;
+  else if (i==2) printf " %-22s", $i;
+  else printf " %-s", $i;
+};
+printf "\n";
+}'
+
 fi
 
 
